# Site settings
title: zimulala Blog
email: zimu_xia@126.com
description: "To be or not to be ..."
baseurl: "http://zimulala.github.io"
url: "http://zimulala.github.io"

category-list: [golang, linux]

# Build settings
markdown: kramdown
permalink: pretty
